### ISSUE TITLE
NoSuchMethodError GeneratedMessageV3.isStringEmpty()

### ISSUE THREAD

**Issue by ngocthach** [googleapis/java-dialogflow-cx#460]
Error:

Exception in thread "grpc-default-executor-0" java.lang.NoSuchMethodError: 'boolean com.google.protobuf.GeneratedMessageV3.isStringEmpty(java.lang.Object)'
	at com.google.cloud.dialogflow.cx.v3.ListAgentsRequest.getSerializedSize(ListAgentsRequest.java:282)
	at io.grpc.protobuf.lite.ProtoInputStream.available(ProtoInputStream.java:108)
	at io.grpc.internal.MessageFramer.getKnownLength(MessageFramer.java:205)
	at io.grpc.internal.MessageFramer.writePayload(MessageFramer.java:137)
	at io.grpc.internal.AbstractStream.writeMessage(AbstractStream.java:65)
	at io.grpc.internal.ForwardingClientStream.writeMessage(ForwardingClientStream.java:37)
	at io.grpc.internal.DelayedStream$6.run(DelayedStream.java:283)
	at io.grpc.internal.DelayedStream.drainPendingCalls(DelayedStream.java:182)
	at io.grpc.internal.DelayedStream.access$100(DelayedStream.java:44)
	at io.grpc.internal.DelayedStream$4.run(DelayedStream.java:148)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

#### Environment details

1. DialogFlow-Cx: 0.11.0
2. OS type and version: ubuntu-20.04
3. Java version: 
 openjdk 11.0.14.1 2022-02-08
 OpenJDK Runtime Environment (build 11.0.14.1+1-Ubuntu-0ubuntu1.20.04)
 OpenJDK 64-Bit Server VM (build 11.0.14.1+1-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)

4. io.grpc: 1.43.2
5. com.google.protobuf: java, java-util: 3.19.2

Thanks!

**Comment by ngocthach** [comment]
Protobuf issue close: https://github.com/protocolbuffers/protobuf/issues/9236

**Comment by galz10** [comment]
Hi @ngocthach could you provide more information on the issue like code you used that caused this error. With the current information i can not reproduce this issue.

**Comment by ngocthach** [comment]
Here, my code:

`
import com.google.api.core.ApiFuture
import com.google.cloud.dialogflow.cx.v3.AgentsClient
import com.google.cloud.dialogflow.cx.v3.IntentsClient
import com.google.cloud.dialogflow.cx.v3.EntityTypesClient
import com.google.cloud.dialogflow.cx.v3.FlowsClient
import com.google.cloud.dialogflow.cx.v3.PagesClient
import com.google.cloud.dialogflow.cx.v3.WebhooksClient
interface DialogflowCXManager {
  fun getListAgents(agentId: String): ApiFuture<AgentsClient.ListAgentsPagedResponse>
  fun getListIntents(agentId: String): ApiFuture<IntentsClient.ListIntentsPagedResponse>
  fun getListEntityTypes(agentId: String): ApiFuture<EntityTypesClient.ListEntityTypesPagedResponse>
  fun getListFlows(agentId: String): ApiFuture<FlowsClient.ListFlowsPagedResponse>
  fun getListPages(flowInfo: String): ApiFuture<PagesClient.ListPagesPagedResponse>
  fun getListWebhooks(agentId: String): ApiFuture<WebhooksClient.ListWebhooksPagedResponse>
}`


`

import com.google.api.core.ApiAsyncFunction
import com.google.api.core.ApiFuture
import com.google.api.core.ApiFutures
import javax.inject.Inject
import vn.com.momo.flags.Flags
import vn.com.momo.flags.Flag
import com.google.cloud.dialogflow.cx.v3.AgentsClient
import com.google.cloud.dialogflow.cx.v3.AgentsSettings
import com.google.cloud.dialogflow.cx.v3.IntentsClient
import com.google.cloud.dialogflow.cx.v3.IntentsSettings
import com.google.cloud.dialogflow.cx.v3.EntityTypesClient
import com.google.cloud.dialogflow.cx.v3.EntityTypesSettings
import com.google.cloud.dialogflow.cx.v3.FlowsClient
import com.google.cloud.dialogflow.cx.v3.FlowsSettings
import com.google.cloud.dialogflow.cx.v3.PagesClient
import com.google.cloud.dialogflow.cx.v3.PagesSettings
import com.google.cloud.dialogflow.cx.v3.WebhooksClient
import com.google.cloud.dialogflow.cx.v3.WebhooksSettings
import java.util.concurrent.Executors
class DialogflowCXManagerImpl @Inject internal constructor() : DialogflowCXManager {
    companion object{
        val projectId: Flag<String> = Flags.create(
            "dialogflowCX.project_id",
            "Project ID for running DialogflowCX",
            "momovn-dev"
        )
        val locationId: Flag<String> = Flags.create(
            "dialogflowCX.location",
            "Location for running DialogflowCX",
            "us-central1"
        )
    }
    private val agentClient = createAgentClient(locationId.value()!!)
    private val intentClient = createIntentClient(locationId.value()!!)
    private val pageClient = createPageClient(locationId.value()!!)
    private val flowClient = createFlowClient(locationId.value()!!)
    private val entityClient = createEntityClient(locationId.value()!!)
    private val webhookClient = createWebhookClient(locationId.value()!!)
    private val executors = Executors.newFixedThreadPool(16)
    private fun createAgentClient(locationId: String):ApiFuture<AgentsClient>{
        val agentsSettingsBuilder = AgentsSettings.newBuilder()
        agentsSettingsBuilder.endpoint = getEndpoint(locationId)
        val agentsSettings = agentsSettingsBuilder.build()
        return ApiFutures.immediateFuture(AgentsClient.create(agentsSettings))
    }
    private fun createIntentClient(locationId: String):ApiFuture<IntentsClient>{
        val intentsSettingsBuilder = IntentsSettings.newBuilder()
        intentsSettingsBuilder.endpoint = getEndpoint(locationId)
        val intentsSettings = intentsSettingsBuilder.build()
        return ApiFutures.immediateFuture(IntentsClient.create(intentsSettings))
    }
    private fun createPageClient(locationId: String):ApiFuture<PagesClient>{
        val pagesSettingsBuilder: PagesSettings.Builder = PagesSettings.newBuilder()
        pagesSettingsBuilder.endpoint = getEndpoint(locationId)
        val pagesSettings = pagesSettingsBuilder.build()
        return ApiFutures.immediateFuture(PagesClient.create(pagesSettings))
    }
    private fun createFlowClient(locationId: String):ApiFuture<FlowsClient>{
        val flowsSettingsBuilder: FlowsSettings.Builder = FlowsSettings.newBuilder()
        flowsSettingsBuilder.endpoint = getEndpoint(locationId)
        val flowsSettings = flowsSettingsBuilder.build()
        return ApiFutures.immediateFuture(FlowsClient.create(flowsSettings))
    }
    private fun createEntityClient(locationId: String):ApiFuture<EntityTypesClient>{
        val entitySettingsBuilder: EntityTypesSettings.Builder = EntityTypesSettings.newBuilder()
        entitySettingsBuilder.endpoint = getEndpoint(locationId)
        val entitySettings = entitySettingsBuilder.build()
        return ApiFutures.immediateFuture(EntityTypesClient.create(entitySettings))
    }
    private fun createWebhookClient(locationId: String): ApiFuture<WebhooksClient>{
        val webhookSettingsBuilder: WebhooksSettings.Builder = WebhooksSettings.newBuilder()
        webhookSettingsBuilder.endpoint = getEndpoint(locationId)
        val webhookSettings = webhookSettingsBuilder.build()
        return ApiFutures.immediateFuture(WebhooksClient.create(webhookSettings))
    }
    private fun getAgentInfo(agentId: String): String{
        return "projects/${projectId.value()}/locations/${locationId.value()}/agents/${agentId}"
    }
    private fun getEndpoint(locationId: String):String{
        if (locationId == "global") {
            return "dialogflow.googleapis.com:443"
        }
        return "$locationId-dialogflow.googleapis.com:443"
    }
    override fun getListAgents(agentId: String): ApiFuture<AgentsClient.ListAgentsPagedResponse> {
        //API request for list of agents
        return ApiFutures.transformAsync(
            agentClient,
            ApiAsyncFunction { client ->
                return@ApiAsyncFunction ApiFutures.immediateFuture((client.listAgents(getAgentInfo(agentId))))
            },
            executors
        )
    }
    override fun getListIntents(agentId: String): ApiFuture<IntentsClient.ListIntentsPagedResponse> {
        //API request for list of intents
        return ApiFutures.transformAsync(
            intentClient,
            ApiAsyncFunction { client ->
                return@ApiAsyncFunction ApiFutures.immediateFuture((client.listIntents(getAgentInfo(agentId))))
            },
            executors
        )
    }
    override fun getListEntityTypes(agentId: String): ApiFuture<EntityTypesClient.ListEntityTypesPagedResponse> {
        //API request for list of entity types
        return ApiFutures.transformAsync(
            entityClient,
            ApiAsyncFunction { client ->
                return@ApiAsyncFunction ApiFutures.immediateFuture((client.listEntityTypes(getAgentInfo(agentId))))
            },
            executors
        )
    }
    override fun getListFlows(agentId: String): ApiFuture<FlowsClient.ListFlowsPagedResponse> {
        //API request for list of flow
        return ApiFutures.transformAsync(
            flowClient,
            ApiAsyncFunction { client ->
                return@ApiAsyncFunction ApiFutures.immediateFuture((client.listFlows(getAgentInfo(agentId))))
            },
            executors
        )
    }
    override fun getListPages(flowInfo: String): ApiFuture<PagesClient.ListPagesPagedResponse> {
        //API request for list of pages corresponding to a flow
        return ApiFutures.transformAsync(
            pageClient,
            ApiAsyncFunction { client ->
                return@ApiAsyncFunction ApiFutures.immediateFuture((client.listPages(getAgentInfo(flowInfo))))
            },
            executors
        )
    }
    override fun getListWebhooks(agentId: String): ApiFuture<WebhooksClient.ListWebhooksPagedResponse> {
        //API request for list of webhook
        return ApiFutures.transformAsync(
            webhookClient,
            ApiAsyncFunction { client ->
                return@ApiAsyncFunction ApiFutures.immediateFuture((client.listWebhooks(getAgentInfo(agentId))))
            },
            executors
        )
    }
}

`

**Comment by galz10** [comment]
Closing due to inactivity, if you're still having this issue feel free to open it again.
